FROM jrei/systemd-ubuntu:20.04

# Disable frontend dialogs while installing packages
ENV DEBIAN_FRONTEND=non-interactive

# Install SSH server
RUN apt update \
    && apt install -y openssh-server sudo \
    && mkdir /var/run/sshd

# Set root password
RUN echo 'root:root' | chpasswd

# Add a new user 'admin'
RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1000 admin

# Set password for the 'admin' user
RUN echo 'admin:admin' | chpasswd

# Create .ssh directory and authorized_keys file for root and admin
RUN mkdir -p /root/.ssh /home/admin/.ssh \
    && touch /root/.ssh/authorized_keys /home/admin/.ssh/authorized_keys

# Start SSH service
RUN service ssh start

# Expose SSH port
EXPOSE 22

# Install utility tools
RUN apt-get install -y vim net-tools netcat less

# Run SSH service in the background and keep the container running
# CMD [ "sh", "-c", "service ssh start; sleep infinity" ]

CMD ["/lib/systemd/systemd"]
